import { Injectable } from '@angular/core';
import { ICountryModel } from './model/country-model';

@Injectable({
  providedIn: 'root'
})
export class RLIntlPhoneService {

  constructor() { }

 /**
  * Return the list of Countrymodel.
  */
 GetCountryList() {
  let CountryList: ICountryModel[] = [];
  CountryList.push({ isoCode: "AD", name: "Andorra", flagCssClass: "flag-ad", inputMasking: "999 999", countryPhoneCode:"+376 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AE", name: "United Arab Emirates", flagCssClass: "flag-ae", inputMasking: "999 999 9999", countryPhoneCode:"+971 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AF", name: "Afghanistan", flagCssClass: "flag-af", inputMasking: "999 999 9999", countryPhoneCode:"+93 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AG", name: "Antigua and Barbuda", flagCssClass: "flag-ag", inputMasking: "999-9999", countryPhoneCode:"+1 (268) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AI", name: "Anguilla", flagCssClass: "flag-ai", inputMasking: "999-9999", countryPhoneCode:"+1 (264) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AL", name: "Albania", flagCssClass: "flag-al", inputMasking: "999 999 9999", countryPhoneCode:"+355 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AM", name: "Armenia", flagCssClass: "flag-am", inputMasking: "999 999999", countryPhoneCode:"+374 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AN", name: "Netherlands Antilles", flagCssClass: "flag-an", inputMasking: "999 9999", countryPhoneCode:"+599 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AO", name: "Angola", flagCssClass: "flag-ao", inputMasking: "999 999 999", countryPhoneCode:"+244 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AQ", name: "Antarctica", flagCssClass: "flag-aq", inputMasking: "9 99999", countryPhoneCode:"+672 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AR", name: "Argentina", flagCssClass: "flag-ar", inputMasking: "999 99-9999-9999", countryPhoneCode:"+54 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "AS", name: "American Samoa", flagCssClass: "flag-as", inputMasking: "999-9999", countryPhoneCode:"+1 (684) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AT", name: "Austria", flagCssClass: "flag-at", inputMasking: "9999 999999", countryPhoneCode:"+43 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AU", name: "Australia", flagCssClass: "flag-au", inputMasking: "9999 999 999", countryPhoneCode:"+61 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AW", name: "Aruba", flagCssClass: "flag-aw", inputMasking: "999 9999", countryPhoneCode:"+297 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "AZ", name: "Azerbaijan", flagCssClass: "flag-az", inputMasking: "999 999 99 99", countryPhoneCode:"+994 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BA", name: "Bosnia and Herzegovina", flagCssClass: "flag-ba", inputMasking: "999 999 999", countryPhoneCode:"+387 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BB", name: "Barbados", flagCssClass: "flag-bb", inputMasking: "999-9999", countryPhoneCode:"+1 (246) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BD", name: "Bangladesh", flagCssClass: "flag-bd", inputMasking: "99999-999999", countryPhoneCode:"+880 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BE", name: "Belgium", flagCssClass: "flag-be", inputMasking: "9999 99 99 99", countryPhoneCode:"+32 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BF", name: "Burkina Faso", flagCssClass: "flag-bf", inputMasking: "99 99 99 99", countryPhoneCode:"+226 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "BG", name: "Bulgaria", flagCssClass: "flag-bg", inputMasking: "999 999 999", countryPhoneCode:"+359 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BH", name: "Bahrain", flagCssClass: "flag-bh", inputMasking: "9999 9999", countryPhoneCode:"+973 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BI", name: "Burundi", flagCssClass: "flag-bi", inputMasking: "99 99 99 99", countryPhoneCode:"+257 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BJ", name: "Benin", flagCssClass: "flag-bj", inputMasking: "99 99 99 99", countryPhoneCode:"+229 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BL", name: "Saint Barthelemy", flagCssClass: "flag-bl", inputMasking: "9999 99 99 99", countryPhoneCode:"+590 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BM", name: "Bermuda", flagCssClass: "flag-bm", inputMasking: "999-9999", countryPhoneCode:"+1 (441) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BN", name: "Brunei", flagCssClass: "flag-bn", inputMasking: "999 9999", countryPhoneCode:"+673 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BO", name: "Bolivia", flagCssClass: "flag-bo", inputMasking: "99999999", countryPhoneCode:"+591 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BR", name: "Brazil", flagCssClass: "flag-br", inputMasking: "(99) 99999-9999", countryPhoneCode:"+55 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BS", name: "Bahamas", flagCssClass: "flag-bs", inputMasking: "999-9999", countryPhoneCode:"+1 (242) ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "BT", name: "Bhutan", flagCssClass: "flag-bt", inputMasking: "99 99 99 99", countryPhoneCode:"+975 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BW", name: "Botswana", flagCssClass: "flag-bw", inputMasking: "99 999 999", countryPhoneCode:"+267 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BY", name: "Belarus", flagCssClass: "flag-by", inputMasking: "9 999 999-99-99", countryPhoneCode:"+375 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "BZ", name: "Belize", flagCssClass: "flag-bz", inputMasking: "999-9999", countryPhoneCode:"+501 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CA", name: "Canada", flagCssClass: "flag-ca", inputMasking: "(999) 999-9999", countryPhoneCode:"+1 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CC", name: "Cocos Islands", flagCssClass: "flag-cc", inputMasking: "9999 999 999", countryPhoneCode:"+61 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CD", name: "Democratic Republic of the Congo", flagCssClass: "flag-cd", inputMasking: "9999 999 999", countryPhoneCode:"+243 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CF", name: "Central African Republic", flagCssClass: "flag-cf", inputMasking: "99 99 99 99", countryPhoneCode:"+236 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CG", name: "Republic of the Congo", flagCssClass: "flag-cg", inputMasking: " 99 999 9999", countryPhoneCode:"+242 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CH", name: "Switzerland", flagCssClass: "flag-ch", inputMasking: "999 999 99 99", countryPhoneCode:"+41 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "CI", name: "Ivory Coast", flagCssClass: "flag-ci", inputMasking: "99 99 99 99", countryPhoneCode:"+225 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CK", name: "Cook Islands", flagCssClass: "flag-ck", inputMasking: "99 9999", countryPhoneCode:"+682 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CL", name: "Chile", flagCssClass: "flag-cl", inputMasking: "9 9999 9999", countryPhoneCode:"+56 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CM", name: "Cameroon", flagCssClass: "flag-cm", inputMasking: "9 99 99 99 99", countryPhoneCode:"+237 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CN", name: "China", flagCssClass: "flag-cn", inputMasking: "999 9999 9999", countryPhoneCode:"+86 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CO", name: "Colombia", flagCssClass: "flag-co", inputMasking: "999 9999999", countryPhoneCode:"+57 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CR", name: "Costa Rica", flagCssClass: "flag-cr", inputMasking: "9999 9999", countryPhoneCode:"+506 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CU", name: "Cuba", flagCssClass: "flag-cu", inputMasking: "99 9999999", countryPhoneCode:"+53 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CV", name: "Cape Verde", flagCssClass: "flag-cv", inputMasking: "999 99 99", countryPhoneCode:"+238 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CW", name: "Curacao", flagCssClass: "flag-cw", inputMasking: "999 9999", countryPhoneCode:"+599 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "CX", name: "Christmas Island", flagCssClass: "flag-cx", inputMasking: "9999 999 999", countryPhoneCode:"+61 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CY", name: "Cyprus", flagCssClass: "flag-cy", inputMasking: "99 999999", countryPhoneCode:"+357 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "CZ", name: "Czech Republic", flagCssClass: "flag-cz", inputMasking: "999 999 999", countryPhoneCode:"+420 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DE", name: "Germany", flagCssClass: "flag-de", inputMasking: "99999 9999999", countryPhoneCode:"+49 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DJ", name: "Djibouti", flagCssClass: "flag-dj", inputMasking: "99 99 99 99", countryPhoneCode:"+253 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DK", name: "Denmark", flagCssClass: "flag-dk", inputMasking: "99 99 99 99", countryPhoneCode:"+45 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DM", name: "Dominica", flagCssClass: "flag-dm", inputMasking: "999-9999", countryPhoneCode:"+1 (767) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DO", name: "Dominican Republic", flagCssClass: "flag-do", inputMasking: "999-9999", countryPhoneCode:"+1 (809) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "DZ", name: "Algeria", flagCssClass: "flag-dz", inputMasking: "9999 99 99 99", countryPhoneCode:"+213 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "EC", name: "Ecuador", flagCssClass: "flag-ec", inputMasking: "999 999 9999", countryPhoneCode:"+593 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "EE", name: "Estonia", flagCssClass: "flag-ee", inputMasking: "9999 9999", countryPhoneCode:"+372 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "EG", name: "Egypt", flagCssClass: "flag-eg", inputMasking: "9999 999 9999", countryPhoneCode:"+20 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "EH", name: "Western Sahara", flagCssClass: "flag-eh", inputMasking: "9999-999999", countryPhoneCode:"+212 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ER", name: "Eritrea", flagCssClass: "flag-er", inputMasking: "99 999 999", countryPhoneCode:"+291 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ES", name: "Spain", flagCssClass: "flag-es", inputMasking: "999 99 99 99", countryPhoneCode:"+34 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ET", name: "Ethiopia", flagCssClass: "flag-et", inputMasking: "999 999 9999", countryPhoneCode:"+251 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "FI", name: "Finland", flagCssClass: "flag-fi", inputMasking: "999 9999999", countryPhoneCode:"+358 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "FJ", name: "Fiji", flagCssClass: "flag-fj", inputMasking: "999 9999", countryPhoneCode:"+679 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "FK", name: "Falkland Islands", flagCssClass: "flag-fk", inputMasking: "99999", countryPhoneCode:"+500 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "FM", name: "Micronesia", flagCssClass: "flag-fm", inputMasking: "999 9999", countryPhoneCode:"+691 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "FO", name: "Faroe Islands", flagCssClass: "flag-fo", inputMasking: "999999", countryPhoneCode:"+298 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "FR", name: "France", flagCssClass: "flag-fr", inputMasking: "99 99 99 99 99", countryPhoneCode:"+33 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GA", name: "Gabon", flagCssClass: "flag-ga", inputMasking: "99 99 99 99", countryPhoneCode:"+241 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GB", name: "United Kingdom", flagCssClass: "flag-gb", inputMasking: "99999 99999", countryPhoneCode:"+44 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GD", name: "Grenada", flagCssClass: "flag-gd", inputMasking: "999-9999", countryPhoneCode:"+1 (473) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GE", name: "Georgia", flagCssClass: "flag-ge", inputMasking: "999 99 99 99", countryPhoneCode:"+995 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GG", name: "Guernsey", flagCssClass: "flag-gg", inputMasking: "99999 999999", countryPhoneCode:"+44 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GH", name: "Ghana", flagCssClass: "flag-gh", inputMasking: "999 999 9999", countryPhoneCode:"+233 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GI", name: "Gibraltar", flagCssClass: "flag-gi", inputMasking: "99999999", countryPhoneCode:"+350 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GL", name: "Greenland", flagCssClass: "flag-gl", inputMasking: "99 99 99", countryPhoneCode:"+299 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GM", name: "Gambia", flagCssClass: "flag-gm", inputMasking: "999 9999", countryPhoneCode:"+220 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GN", name: "Guinea", flagCssClass: "flag-gn", inputMasking: "999 99 99 99", countryPhoneCode:"+224 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GQ", name: "Equatorial Guinea", flagCssClass: "flag-gq", inputMasking: "999 999 999", countryPhoneCode:"+240 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GR", name: "Greece", flagCssClass: "flag-gr", inputMasking: "999 999 9999", countryPhoneCode:"+30 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GT", name: "Guatemala", flagCssClass: "flag-gt", inputMasking: "9999 9999", countryPhoneCode:"+502 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GU", name: "Guam", flagCssClass: "flag-gu", inputMasking: "999-9999", countryPhoneCode:"+1 (671) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GW", name: "Guinea-Bissau", flagCssClass: "flag-gw", inputMasking: "999 999 999", countryPhoneCode:"+245 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "GY", name: "Guyana", flagCssClass: "flag-gy", inputMasking: "999 9999", countryPhoneCode:"+592 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "HK", name: "Hong Kong", flagCssClass: "flag-hk", inputMasking: "9999 9999", countryPhoneCode:"+852 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "HN", name: "Honduras", flagCssClass: "flag-hn", inputMasking: "9999-9999", countryPhoneCode:"+504 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "HR", name: "Croatia", flagCssClass: "flag-hr", inputMasking: "999 999 9999", countryPhoneCode:"+385 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "HT", name: "Haiti", flagCssClass: "flag-ht", inputMasking: "99 99 9999", countryPhoneCode:"+509 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "HU", name: "Hungary", flagCssClass: "flag-hu", inputMasking: "(99) 999 9999", countryPhoneCode:"+36 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ID", name: "Indonesia", flagCssClass: "flag-id", inputMasking: "9999-999-999", countryPhoneCode:"+62 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IE", name: "Ireland", flagCssClass: "flag-ie", inputMasking: "999 999 9999", countryPhoneCode:"+353 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IL", name: "Israel", flagCssClass: "flag-il", inputMasking: "999-999-9999", countryPhoneCode:"+972 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IM", name: "Isle of Man", flagCssClass: "flag-im", inputMasking: "99999 999999", countryPhoneCode:"+44 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IN", name: "India", flagCssClass: "flag-in", inputMasking: "99999 99999", countryPhoneCode:"+91 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IO", name: "British Indian Ocean Territory", flagCssClass: "flag-io", inputMasking: "999 9999", countryPhoneCode:"+246 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IQ", name: "Iraq", flagCssClass: "flag-iq", inputMasking: "9999 999 9999", countryPhoneCode:"+964 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IR", name: "Iran", flagCssClass: "flag-ir", inputMasking: "9999 999 9999", countryPhoneCode:"+98 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IS", name: "Iceland", flagCssClass: "flag-is", inputMasking: "999 9999", countryPhoneCode:"+354 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "IT", name: "Italy", flagCssClass: "flag-it", inputMasking: "999 999 9999", countryPhoneCode:"+39 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "JE", name: "Jersey", flagCssClass: "flag-je", inputMasking: "99999 999999", countryPhoneCode:"+44 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "JM", name: "Jamaica", flagCssClass: "flag-jm", inputMasking: "999-9999", countryPhoneCode:"+1 (876) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "JO", name: "Jordan", flagCssClass: "flag-jo", inputMasking: "99 9999 9999", countryPhoneCode:"+962 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "JP", name: "Japan", flagCssClass: "flag-jp", inputMasking: "999 9999-9999", countryPhoneCode:"+81 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "KE", name: "Kenya", flagCssClass: "flag-ke", inputMasking: "9999 999999", countryPhoneCode:"+254 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KG", name: "Kyrgyzstan", flagCssClass: "flag-kg", inputMasking: "9999 999 999", countryPhoneCode:"+996 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KH", name: "Cambodia", flagCssClass: "flag-kh", inputMasking: "999 999 999", countryPhoneCode:"+855 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KI", name: "Kiribati", flagCssClass: "flag-ki", inputMasking: "99999999", countryPhoneCode:"+686 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KM", name: "Comoros", flagCssClass: "flag-km", inputMasking: "999 99 99", countryPhoneCode:"+269 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KN", name: "Saint Kitts and Nevis", flagCssClass: "flag-kn", inputMasking: "999-9999", countryPhoneCode:"+1 (869) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KP", name: "North Korea", flagCssClass: "flag-kp", inputMasking: "9999 999 9999", countryPhoneCode:"+850 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KR", name: "South Korea", flagCssClass: "flag-kr", inputMasking: "999-9999-9999", countryPhoneCode:"+82 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KW", name: "Kuwait", flagCssClass: "flag-kw", inputMasking: "999 99999", countryPhoneCode:"+965 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KY", name: "Cayman Islands", flagCssClass: "flag-ky", inputMasking: "999-9999", countryPhoneCode:"+1 (345) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "KZ", name: "Kazakhstan", flagCssClass: "flag-kz", inputMasking: "9 (999) 999 9999", countryPhoneCode:"+7 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LA", name: "Laos", flagCssClass: "flag-la", inputMasking: "999 99 999 999", countryPhoneCode:"+856 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LB", name: "Lebanon", flagCssClass: "flag-lb", inputMasking: "99 999 999", countryPhoneCode:"+961 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LC", name: "Saint Lucia", flagCssClass: "flag-lc", inputMasking: "999-9999", countryPhoneCode:"+1 (758) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LI", name: "Liechtenstein", flagCssClass: "flag-li", inputMasking: "999 999 999", countryPhoneCode:"+423 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LK", name: "Sri Lanka", flagCssClass: "flag-lk", inputMasking: "999 999 9999", countryPhoneCode:"+94 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LR", name: "Liberia", flagCssClass: "flag-lr", inputMasking: "999 999 9999", countryPhoneCode:"+231 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LS", name: "Lesotho", flagCssClass: "flag-ls", inputMasking: "9999 9999", countryPhoneCode:"+266 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LT", name: "Lithuania", flagCssClass: "flag-lt", inputMasking: "(9-999) 99999", countryPhoneCode:"+370 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "LU", name: "Luxembourg", flagCssClass: "flag-lu", inputMasking: "999 999 999", countryPhoneCode:"+352 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LV", name: "Latvia", flagCssClass: "flag-lv", inputMasking: "99 999 999", countryPhoneCode:"+371 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "LY", name: "Libya", flagCssClass: "flag-ly", inputMasking: "999-9999999", countryPhoneCode:"+218 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MA", name: "Morocco", flagCssClass: "flag-ma", inputMasking: "9999-999999", countryPhoneCode:"+212 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MC", name: "Monaco", flagCssClass: "flag-mc", inputMasking: "99 99 99 99 99", countryPhoneCode:"+377 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MD", name: "Moldova", flagCssClass: "flag-md", inputMasking: "9999 99 999", countryPhoneCode:"+373 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ME", name: "Montenegro", flagCssClass: "flag-me", inputMasking: "999 999 999", countryPhoneCode:"+382 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MF", name: "Saint Martin", flagCssClass: "flag-mf", inputMasking: "9999 99 99 99", countryPhoneCode:"+590 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MG", name: "Madagascar", flagCssClass: "flag-mg", inputMasking: "999 99 999 99", countryPhoneCode:"+261 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MH", name: "Marshall Islands", flagCssClass: "flag-mh", inputMasking: "999-9999", countryPhoneCode:"+692 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MK", name: "Macedonia", flagCssClass: "flag-mk", inputMasking: "999 999 999", countryPhoneCode:"+389 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ML", name: "Mali", flagCssClass: "flag-ml", inputMasking: "99 99 99 99", countryPhoneCode:"+223 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MM", name: "Myanmar", flagCssClass: "flag-mm", inputMasking: "99 999 9999", countryPhoneCode:"+95 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MN", name: "Mongolia", flagCssClass: "flag-mn", inputMasking: "9999 9999", countryPhoneCode:"+976 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MO", name: "Macau", flagCssClass: "flag-mo", inputMasking: "9999 9999", countryPhoneCode:"+853 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MP", name: "Northern Mariana Islands", flagCssClass: "flag-mp", inputMasking: "999-9999", countryPhoneCode:"+1 (670) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MR", name: "Mauritania", flagCssClass: "flag-mr", inputMasking: "99 99 99 99", countryPhoneCode:"+222 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MS", name: "Montserrat", flagCssClass: "flag-ms", inputMasking: "999-9999", countryPhoneCode:"+1 (664) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MT", name: "Malta", flagCssClass: "flag-mt", inputMasking: "9999 9999", countryPhoneCode:"+356 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "MU", name: "Mauritius", flagCssClass: "flag-mu", inputMasking: "9999 9999", countryPhoneCode:"+230 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MV", name: "Maldives", flagCssClass: "flag-mv", inputMasking: "999-9999", countryPhoneCode:"+960 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MW", name: "Malawi", flagCssClass: "flag-mw", inputMasking: "9999 99 99 99", countryPhoneCode:"+265 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MX", name: "Mexico", flagCssClass: "flag-mx", inputMasking: "999 999 999 9999", countryPhoneCode:"+52 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MY", name: "Malaysia", flagCssClass: "flag-my", inputMasking: "999-999 9999", countryPhoneCode:"+60 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "MZ", name: "Mozambique", flagCssClass: "flag-mz", inputMasking: "99 999 9999", countryPhoneCode:"+258 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NA", name: "Namibia", flagCssClass: "flag-na", inputMasking: "999 999 9999", countryPhoneCode:"+264 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NC", name: "New Caledonia", flagCssClass: "flag-nc", inputMasking: "99 99 99", countryPhoneCode:"+687 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NE", name: "Niger", flagCssClass: "flag-ne", inputMasking: "99 99 99 99", countryPhoneCode:"+227 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NG", name: "Nigeria", flagCssClass: "flag-ng", inputMasking: "9999 999 9999", countryPhoneCode:"+234 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NI", name: "Nicaragua", flagCssClass: "flag-ni", inputMasking: "9999 9999", countryPhoneCode:"+505 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NL", name: "Netherlands", flagCssClass: "flag-nl", inputMasking: "99 99999999", countryPhoneCode:"+31 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NO", name: "Norway", flagCssClass: "flag-no", inputMasking: "999 99 999", countryPhoneCode:"+47 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NP", name: "Nepal", flagCssClass: "flag-np", inputMasking: "999-9999999", countryPhoneCode:"+977 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NR", name: "Nauru", flagCssClass: "flag-nr", inputMasking: "999 9999", countryPhoneCode:"+674 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NU", name: "Niue", flagCssClass: "flag-nu", inputMasking: "999 9999", countryPhoneCode:"+683 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "NZ", name: "New Zealand", flagCssClass: "flag-nz", inputMasking: "999 999 9999", countryPhoneCode:"+64 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "OM", name: "Oman", flagCssClass: "flag-om", inputMasking: "9999 9999", countryPhoneCode:"+968 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PA", name: "Panama", flagCssClass: "flag-pa", inputMasking: "9999-9999", countryPhoneCode:"+507 ", isShowCustomFlag: false });  
  CountryList.push({ isoCode: "PE", name: "Peru", flagCssClass: "flag-pe", inputMasking: "999 999 999", countryPhoneCode:"+51 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PF", name: "French Polynesia", flagCssClass: "flag-pf", inputMasking: "99 99 99 99", countryPhoneCode:"+689 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PG", name: "Papua New Guinea", flagCssClass: "flag-pg", inputMasking: "9999 9999", countryPhoneCode:"+675 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PH", name: "Philippines", flagCssClass: "flag-ph", inputMasking: "9999 999 9999", countryPhoneCode:"+63 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PK", name: "Pakistan", flagCssClass: "flag-pk", inputMasking: "9999 9999999", countryPhoneCode:"+92 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PL", name: "Poland", flagCssClass: "flag-pl", inputMasking: "999 999 999", countryPhoneCode:"+48 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PM", name: "Saint Pierre and Miquelon", flagCssClass: "flag-pm", inputMasking: "999 99 99", countryPhoneCode:"+508 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PN", name: "Pitcairn", flagCssClass: "flag-pn", inputMasking: "99 999999", countryPhoneCode:"+64 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PR", name: "Puerto Rico", flagCssClass: "flag-pr", inputMasking: "999-9999", countryPhoneCode:"+1 (787) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PS", name: "Palestine", flagCssClass: "flag-ps", inputMasking: "9999 999 999", countryPhoneCode:"+970 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PT", name: "Portugal", flagCssClass: "flag-pt", inputMasking: "999 999 999", countryPhoneCode:"+351 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PW", name: "Palau", flagCssClass: "flag-pw", inputMasking: "999 9999", countryPhoneCode:"+680 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "PY", name: "Paraguay", flagCssClass: "flag-py", inputMasking: "9999 999999", countryPhoneCode:"+595 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "QA", name: "Qatar", flagCssClass: "flag-qa", inputMasking: "9999 9999", countryPhoneCode:"+974 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "RE", name: "Reunion", flagCssClass: "flag-re", inputMasking: "9999 99 99 99", countryPhoneCode:"+262 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "RO", name: "Romania", flagCssClass: "flag-ro", inputMasking: "9999 999 999", countryPhoneCode:"+40 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "RS", name: "Serbia", flagCssClass: "flag-rs", inputMasking: "999 9999999", countryPhoneCode:"+381 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "RU", name: "Russia", flagCssClass: "flag-ru", inputMasking: "9 (999) 999-99-99", countryPhoneCode:"+7 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "RW", name: "Rwanda", flagCssClass: "flag-rw", inputMasking: "9999 999 999", countryPhoneCode:"+250 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SA", name: "Saudi Arabia", flagCssClass: "flag-sa", inputMasking: "999 999 9999", countryPhoneCode:"+966 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SB", name: "Solomon Islands", flagCssClass: "flag-sb", inputMasking: "99 99999", countryPhoneCode:"+677 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SC", name: "Seychelles", flagCssClass: "flag-sc", inputMasking: "9 999 999", countryPhoneCode:"+248 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SD", name: "Sudan", flagCssClass: "flag-sd", inputMasking: "999 999 9999", countryPhoneCode:"+249 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SE", name: "Sweden", flagCssClass: "flag-se", inputMasking: "999-999 99 99", countryPhoneCode:"+46 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SG", name: "Singapore", flagCssClass: "flag-sg", inputMasking: "9999 9999", countryPhoneCode:"+65 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SH", name: "Saint Helena", flagCssClass: "flag-sh", inputMasking: "99999", countryPhoneCode:"+290 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SI", name: "Slovenia", flagCssClass: "flag-si", inputMasking: "999 999 999", countryPhoneCode:"+386 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SJ", name: "Svalbard and Jan Mayen", flagCssClass: "flag-sj", inputMasking: "999 99 999", countryPhoneCode:"+47 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SK", name: "Slovakia", flagCssClass: "flag-sk", inputMasking: "9999 999 999", countryPhoneCode:"+421 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SL", name: "Sierra Leone", flagCssClass: "flag-sl", inputMasking: "(999) 999999", countryPhoneCode:"+232 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SM", name: "San Marino", flagCssClass: "flag-sm", inputMasking: "99 99 99 99", countryPhoneCode:"+378 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SN", name: "Senegal", flagCssClass: "flag-sn", inputMasking: "99 999 99 99", countryPhoneCode:"+221 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SO", name: "Somalia", flagCssClass: "flag-so", inputMasking: "9 9999999", countryPhoneCode:"+252 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SR", name: "Suriname", flagCssClass: "flag-sr", inputMasking: "999-9999", countryPhoneCode:"+597 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SS", name: "South Sudan", flagCssClass: "flag-ss", inputMasking: "9999 999 999", countryPhoneCode:"+211 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ST", name: "Sao Tome and Principe", flagCssClass: "flag-st", inputMasking: "999 9999", countryPhoneCode:"+239 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SV", name: "El Salvador", flagCssClass: "flag-sv", inputMasking: "9999 9999", countryPhoneCode:"+503 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SX", name: "Sint Maarten", flagCssClass: "flag-sx", inputMasking: "999-9999", countryPhoneCode:"+1 (721) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SY", name: "Syria", flagCssClass: "flag-sy", inputMasking: "9999 999 999", countryPhoneCode:"+963 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "SZ", name: "Swaziland", flagCssClass: "flag-sz", inputMasking: "9999 9999", countryPhoneCode:"+268 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TC", name: "Turks and Caicos Islands", flagCssClass: "flag-tc", inputMasking: "999-9999", countryPhoneCode:"+1 (649) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TD", name: "Chad", flagCssClass: "flag-td", inputMasking: "99 99 99 99", countryPhoneCode:"+235 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TG", name: "Togo", flagCssClass: "flag-tg", inputMasking: "99 99 99 99", countryPhoneCode:"+228 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TH", name: "Thailand", flagCssClass: "flag-th", inputMasking: "999 999 9999", countryPhoneCode:"+66 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TJ", name: "Tajikistan", flagCssClass: "flag-tj", inputMasking: "999 99 9999", countryPhoneCode:"+992 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TK", name: "Tokelau", flagCssClass: "flag-tk", inputMasking: "9999", countryPhoneCode:"+690 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TL", name: "East Timor", flagCssClass: "flag-tl", inputMasking: "9999 9999", countryPhoneCode:"+670 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TM", name: "Turkmenistan", flagCssClass: "flag-tm", inputMasking: "9 99 999999", countryPhoneCode:"+993 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TN", name: "Tunisia", flagCssClass: "flag-tn", inputMasking: "99 999 999", countryPhoneCode:"+216 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TO", name: "Tonga", flagCssClass: "flag-to", inputMasking: "999 9999", countryPhoneCode:"+676 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TR", name: "Turkey", flagCssClass: "flag-tr", inputMasking: "9999 999 99 99", countryPhoneCode:"+90 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TT", name: "Trinidad and Tobago", flagCssClass: "flag-tt", inputMasking: "999-9999", countryPhoneCode:"+1 (868) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TV", name: "Tuvalu", flagCssClass: "flag-tv", inputMasking: "999999", countryPhoneCode:"+688 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TW", name: "Taiwan", flagCssClass: "flag-tw", inputMasking: "9999 999 999", countryPhoneCode:"+886 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "TZ", name: "Tanzania", flagCssClass: "flag-tz", inputMasking: "9999 999 999", countryPhoneCode:"+255 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "UA", name: "Ukraine", flagCssClass: "flag-ua", inputMasking: "999 999 9999", countryPhoneCode:"+380 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "UG", name: "Uganda", flagCssClass: "flag-ug", inputMasking: "9999 999999", countryPhoneCode:"+256 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "US", name: "United States", flagCssClass: "flag-us", inputMasking: "(999) 999-9999", countryPhoneCode:"+1 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "UY", name: "Uruguay", flagCssClass: "flag-uy", inputMasking: "999 999 999", countryPhoneCode:"+598 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "UZ", name: "Uzbekistan", flagCssClass: "flag-uz", inputMasking: "9 99 999 99 99", countryPhoneCode:"+998 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VA", name: "Vatican", flagCssClass: "flag-va", inputMasking: "999 999 9999", countryPhoneCode:"+39 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VC", name: "Saint Vincent and the Grenadines", flagCssClass: "flag-vc", inputMasking: "999-9999", countryPhoneCode:"+1 (784) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VE", name: "Venezuela", flagCssClass: "flag-ve", inputMasking: "9999-9999999", countryPhoneCode:"+58 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VG", name: "British Virgin Islands", flagCssClass: "flag-vg", inputMasking: "999-9999", countryPhoneCode:"+1 (284) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VI", name: "U.S. Virgin Islands", flagCssClass: "flag-vi", inputMasking: "999-9999", countryPhoneCode:"+1 (340) ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VN", name: "Vietnam", flagCssClass: "flag-vn", inputMasking: "999 999 99 99", countryPhoneCode:"+84 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "VU", name: "Vanuatu", flagCssClass: "flag-vu", inputMasking: "999 9999", countryPhoneCode:"+678 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "WF", name: "Wallis and Futuna", flagCssClass: "flag-wf", inputMasking: "99 99 99", countryPhoneCode:"+681 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "WS", name: "Samoa", flagCssClass: "flag-ws", inputMasking: "99 99999", countryPhoneCode:"+685 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "XK", name: "Kosovo", flagCssClass: "flag-xk", inputMasking: "999 999 999", countryPhoneCode:"+383 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "YE", name: "Yemen", flagCssClass: "flag-ye", inputMasking: "9999 999 999", countryPhoneCode:"+967 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "YT", name: "Mayotte", flagCssClass: "flag-yt", inputMasking: "9999 99 99 99", countryPhoneCode:"+262 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ZA", name: "South Africa", flagCssClass: "flag-za", inputMasking: "999 999 9999", countryPhoneCode:"+27 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ZM", name: "Zambia", flagCssClass: "flag-zm", inputMasking: "999 9999999", countryPhoneCode:"+260 ", isShowCustomFlag: false });
  CountryList.push({ isoCode: "ZW", name: "Zimbabwe", flagCssClass: "flag-zw", inputMasking: "999 999 9999", countryPhoneCode:"+263 ", isShowCustomFlag: false });

return CountryList;
}
}
